### PR TITLE
Add support to reverse DexGuard's resource file name obfuscation

### PR DESCRIPTION
**Pull request by MrHadiSatrio**
### What has changed
- We now support reversing DexGuard's resource file name obfuscation.

### Why was it changed
- Because otherwise attribution for resource files will be broken for projects configured with DexGuard.

### Related issues
- #87 
- #88

### CODE REVIEW

**Comment by MrHadiSatrio** [comment]
To illustrate what I meant by broken attribution, please observe the following table.

| Before | After |
| --- | --- |
| Screen Shot 2022-08-18 at 12 40 48 PM | Screen Shot 2022-08-18 at 12 41 12 PM |
| [Reports.zip](https://github.com/spotify/ruler/files/9370546/Before.zip) | [Reports.zip](https://github.com/spotify/ruler/files/9370527/After.zip) |

**Comment by simonschiller** [comment]
Amazing, thanks a lot for the contribution! I pushed a few commits to better align the changes with the rest of the project, but this should be good to merge if CI is happy.

**Review by simonschiller — APPROVED** [review]

**Comment by MrHadiSatrio** [comment]
My pleasure! Verified that everything still works as expected. 🙌

**Comment by simonschiller** [comment]
Awesome, then let's wait until @ViktorPetrovski or @botronic had time to review the two open PRs and then we can merge them and release a new version that should hopefully be fully compatible with DexGuard and ProGuard.

**Comment by ViktorPetrovski** [comment]
LGTM 👍 Thanks to both of you!

**Review by ViktorPetrovski — APPROVED** [review]

**Pull request merged**
